### ISSUE TITLE
Documentation generator

### ISSUE THREAD

**Issue by kvackkvack** [nanalan/sprinting#1]
Currently, the [documentation generator](https://github.com/cbou/markdox) we use is quite limited. The main problem at the moment is that we want to clearly and cleanly display the full chain of a property (e.g Sprinting.DRAW.Color for some things) -- currently this might not be something to expect of a generator as we do things like
```
function MyClass() { }
Sprinting.DRAW.MyClass = MyClass
```
for classes, but even if you do the very direct
```
Sprinting.DRAW.MyClass = function() { }
```
the generator will parse the function name as just `MyClass`.  
The solution to this without having to switch generator or even make the docs from scratch would be to, for every property/function/class, do:
`@<name/function/class> <the full property chain excluding Sprint>`.
This is, of course, very possible but could get a bit tedious.  
Opinions? Should we switch or keep?

**Comment by nanalan** [comment]
Agreed. Although, you'd need to **find a suitable generator**. I only chose Markdox because it generates Markdown, but we can use whatever is best, obviously.

**Comment by kvackkvack** [comment]
@nanalan didn't close this through his commits adding jsDoc, so I'm doing so now instead.
