### ISSUE TITLE
Links in Documentation

### ISSUE THREAD

**Issue by kvackkvack** [nanalan/sprinting#2]
There should be more links (to other parts of the documentation) in the documentation to make it more easily readable.

**Comment by kvackkvack** [comment]
Assigning @nanalan because he seems to know how to do this.

**Comment by nanalan** [comment]
GHM links titles - i.e.
```markdown
# this
[link to "this"](#this)
```
becomes
```html
<h1><a name='this'>this</a></h1>
<a href='#this'>link to "this"</a>
```
and **link to "this"** will of course link. GitHub changes some titles - like a space ` ` character is replaced by dash `-`.

**Comment by nanalan** [comment]
Also this could be blocked by #1.

**Comment by kvackkvack** [comment]
> Also this could be blocked by #1  

Well, we'd still need proper links, it's just the method that might change.

**Comment by nanalan** [comment]
Yep.

**Comment by kvackkvack** [comment]
Fairly sure this is fixed now thanks to @nanalan. :tada:
