### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by kvackkvack** [nanalan/sprinting#5]
At the moment, if class B inherits from class A, class B lets class A deal with checking types and having defaults for the classes shared arguments.  
However, this might be confusing with the current style of documentation: say the user creates an instance of class B with the code `new B(1, 2, 3, 4)` which then (basically) gets turned into `Object.assign(new A(3, 4), new B(1, 2))`, but A expects two Strings and so the TypeError `new A(): arg 1 must be a String.` gets thrown. Without looking at the documentation, the user won't know exactly which argument caused the problem.  
One possible solution would be to make the error `new A(): arg 1 (x) must be a String.` instead, and that provides at least some clarification as to which argument is causing the error, especially after looking at the stack trace.  
Other ideas?

**Comment by nanalan** [comment]
Perhaps we should change how errors are handled?
I mean, perhaps we should make a helper function for type checking the `arguments` object?

**Comment by kvackkvack** [comment]
Maybe. Perhaps you could have something like
```
populateArguments([Number, 'x'], [Number, 'y']).forEach(arg => this[arg.name] = arg.value) 
```

**Comment by kvackkvack** [comment]
In use it'd look something like 
```
let myFn = function() {
  populateArguments(Array.from(arguments), [Number, 'x', 50], [Number, 'y', 50]).forEach(arg => this[arg.name] = arg.value)
  
  console.log(x, y) // whatever x and y were called with, or their defaults (here, 50 for both)
}
```  
You should also be able to pass a more complicated function instead of a class, something like
`populateArguments(Array.from(arguments), [v => v instanceof Function && !(v.prototype), 'fn'])`

**Comment by nanalan** [comment]
Yeah. Although, es2015 has `function(key=default) {}`...

**Comment by kvackkvack** [comment]
Keeping this non-closed despite the codebase-rebuild as it might become relevant again.

**Comment by nanalan** [comment]
Is fixed now - errors are `<arg-name> must be a(n) <Type>`.
